require 'dotenv'
Dotenv.load
# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 709afdc5f7388031e9cab6af99384cefc4b1be1b5ddb072947ccc33a6a2dc86737b8f06641575ac120e421440d351283fad010c500a525c09f8f11c2c92b4fae

test:
  secret_key_base: c05a3e874f1102fe96fae7f61a1d912a8e15b7af7e6a2096b78e6a31a4037ddc8aae1ad96798bc6d50eaa5d103ea332a2c2a1464f89345c6f9c22f5ccbfcedaf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ENV["SECRET_KEY_BASE"]
